apiVersion: v1
kind: Service
metadata:
  name: prometheus-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 9090
  selector:
    app: prometheus
    component: server
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
