apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: prometheus
    component: server
  ports:
    - name: prometheus
      protocol: TCP
      port: 80
      targetPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - name: grafana
      protocol: TCP
      port: 80
      targetPort: 3000
